### ISSUE TITLE
about hypothesis

### ISSUE THREAD

**Issue by hhaAndroid** [zju-3dv/pvnet#1]
Hello, thank you for making such a high performance algorithm.I have a question about the hypothesis: we randomly choose two pixels and take the intersection of their vectors as a hypothesis hki for the keypoint xk,I don't know what this step means, can you explain it in detail?What is the dimension of the hypothesis? thank you

**Comment by pengsida** [comment]
Choose two pixels and take the intersection of their vectors:
![image](https://user-images.githubusercontent.com/11582122/51298003-c3287500-1a5d-11e9-8df2-c4ab6c11b94b.png)
This figure comes from "PoseCNN: A Convolutional Neural Network for 6D Object Pose Estimation in Cluttered Scenes".

The hypothesis is a candidate point of the target keypoint, and thus its dimension is 2, since the target keypoint is of 2D dimension.

**Comment by hhaAndroid** [comment]
thank you ! I went to see the paper
